### ISSUE TITLE
settings.ws varId bug

### ISSUE THREAD

**Issue by ShuiYu117** [Aelto/tw3-smart-camera#1]
line 37 and line 45 use same varId

**Comment by Aelto** [comment]
Oh indeed, thank you for the notice. They are actually functions for two old sliders that i should remove! I will do it right now.

**Comment by ShuiYu117** [comment]
sorry but i mean both SC_getHorizontalSensitivity() and SC_getOverallSpeed() get value from the varId "SChorizontalSensitivity"

**Comment by Aelto** [comment]
You are right, i saw one of the mistakes but not the other. It is not fixed and should be the last one! Thank you again!
