### ISSUE TITLE
Issue when merging game\player\r4Player.ws

### ISSUE THREAD

**Issue by cocoloco117** [Aelto/tw3-smart-camera#6]
I am having a conflict when merging the smart camera and mod W3EE mods under this block. Getting the following error: 
<img width="1919" alt="Screenshot 2024-06-09 231736" src="https://github.com/Aelto/tw3-smart-camera/assets/172233627/142ee86e-9866-430a-904b-f6244f1ac86c">

Was wondering if this conflict is resolvable? Thank you!

**Comment by Aelto** [comment]
Hello, this can easily be solved by picking B & C. Otherwise you may try the release I just published that should eliminate this merge completely: [smart-camera v1.16](https://github.com/Aelto/tw3-smart-camera/releases/tag/v1.16) !

**Comment by cocoloco117** [comment]
Hello,

Thank you so much. I love playing with your mod!!

Kind regards,

________________________________

**Comment by cocoloco117** [comment]
Hello, I got the same merge conflict and tried merging B&C but it did not work. I also made sure my game is up to date. Not too sure what the problem is :( 
<img width="1658" alt="image" src="https://github.com/Aelto/tw3-smart-camera/assets/172233627/9ef45081-2cec-4d27-9220-505a83db5a59">

**Comment by Aelto** [comment]
You're welcome, i'm glad you're enjoying it thank you!
